### PR TITLE
Upgrade Typescript to v4.2.4

### PR DESCRIPTION
**Pull request by Clarity-89**
Upgrade Typescript to v4.2.4

### CODE REVIEW

**Comment by zoltanbedi** [comment]
Can you also upgrade @typescript-eslint/parser at least 4.16.1 please? This way we won't see the incompatibility warning.

**Comment by Clarity-89** [comment]
> Can you also upgrade @typescript-eslint/parser at least 4.16.1 please? This way we won't see the incompatibility warning.

I bumped it to the latest version, will that work?

**Comment by zoltanbedi** [comment]
Yep that will work, although I think it would be the best to upgrade typescript-eslint/eslint-plugin as well. The only reason I saw because right now there are 2 different versions for the parser.

**Review by zoltanbedi — APPROVED** [review]
🎉

**Comment by Clarity-89** [comment]
@zoltanbedi could you help me with publishing the latest version? I haven't done that before.

**Comment by zoltanbedi** [comment]
It is just running npm publish but you have to be in the grafana org in npmjs to be able to.

**Comment by Clarity-89** [comment]
> It is just running npm publish but you have to be in the grafana org in npmjs to be able to.

Don't think I'm in that org there.

**Pull request merged**
